version: '2'

services:

  mysql:
    build: ./Sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      lan:
        ipv4_address: 192.168.10.2

  node-back:
  #back-end
    build: ./
    ports:
     - "3000:3000"
    depends_on:
     - mysql
    environment:
     - DATABASE_HOST=mysql
    volumes:
     - ./back-end:/app/back-end
    restart: always
    networks: 
      lan:
        ipv4_address: 192.168.10.3
  
  nginx-front:
    build: ./front-end
    ports:
     - "8080:80"
    restart: always
    networks: 
      lan:
        ipv4_address: 192.168.10.4
        
networks:
  lan:
    driver: bridge
    ipam:
      config:
       - subnet: "192.168.10.0/24"
         gateway: "192.168.10.1"
    #Limpiar docker system prune --all 
