## docker-compose para correr wordpress con una base de datos en mysql
## by PeladoNerd https://youtu.be/eoFxMaeB9H4

version: '3.1'

services:

  

  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: da12cb09fe566f2d6e131d7fb5c5c732  
        MYSQL_DATABASE: proyectomodular  
        MYSQL_USER: proyectomodular  
        MYSQL_PASSWORD: da12cb09fe566f2d6e131d7fb5c5c732
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql